// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTR8ZK1TfP5OPSJnJf6l-pDs9AVeiJGLA',
    appId: '1:7789770188:android:bbce140cd9a8cc1011d969',
    messagingSenderId: '7789770188',
    projectId: 'crapapps-65472',
    storageBucket: 'crapapps-65472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZUt1KgBm_OX5apwmO9zK3he4yaXQ7EHA',
    appId: '1:7789770188:ios:77b629d9d170379111d969',
    messagingSenderId: '7789770188',
    projectId: 'crapapps-65472',
    storageBucket: 'crapapps-65472.firebasestorage.app',
    androidClientId: '7789770188-han56qlb8qebe48f75kdircbin698ulb.apps.googleusercontent.com',
    iosClientId: '7789770188-8taofl6kk6vouqqga3icvstrm81g8354.apps.googleusercontent.com',
    iosBundleId: 'com.festival.rumour',
  );

}